fix bug leading to KeyError and change XML output name
- Change xml output to deepvision_updated.xml instead of deepvision.xml
- Fix bug that leads to the folowing error:
   Traceback (most recent call last):
     File "keras_retinanet/bin/predict_DV.py", line 115, in <module>
       csv2xml(PARAMS["xml_file"], csv_file_paths, PARAMS['orientation'])
     File "keras_retinanet/bin/../../keras_retinanet/utils/csv2xml.py", line 195, in csv2xml
       framework_elem = create_framework(csvframedict[child.attrib["time"]])
   KeyError: '20220518200013170'

- Update docker command with a more readable format